services:
  postgres:
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./docker/grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - ./docker/grafana/data:/var/lib/grafana
